version: "3.3"

services:

  traefik:
    image: "traefik:v2.6"
    container_name: "traefik"
    ports:
      - "80:80"
     # - "8080:8080"
    networks:
      - traefik_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # <== Volume for docker admin
      - $PWD/traefik.yaml:/traefik.yaml
      - $PWD/traefik_dynamic.yaml:/traefik_dynamic.yaml
      - $PWD/acme.json:/acme.json
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik_proxy.rule=Host("reverse-proxy.medunes.docker")
      - traefik.http.routers.traefik_proxy.entrypoints=web
      - traefik.http.routers.traefik_proxy.service=api@internal
        #admin:admin
      - traefik.http.middlewares.basic_auth.basicAuth.users=admin:$$apr1$$5p1YvcdH$$nk/pAEmictlfZu2T20QZJ1
      - traefik.http.middlewares.secured_redirect.redirectscheme.scheme=https
      - traefik.http.routers.traefik_proxy.middlewares=basic_auth

networks:
  traefik_net:
    external:
      name: traefik_net
